<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/Chuong2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
def scale(a, v): 
	return [a*vi for vi in v] 
v = [3,5,7] 
scale(10, v) 

[30, 50, 70]

In [2]:
def sumvector(v, w):  
  return [vi+wi for (vi, wi) in zip(v, w)] 
v = [3,5,7] 
w = [2,4,6] 
sumvector(v, w) 

[5, 9, 13]

In [3]:
def dotvector(v, w): 
  	return sum([vi*wi for (vi, wi) in zip(v, w)]) 
dotvector(v, w) 

68

In [4]:
def lenvector(v):  
  return dotvector(v,v) 
lenvector(w) 

56

In [5]:
import numpy as np 
scores  = np.array([-1, 1, 2, -3, 5, -4]) 

In [7]:
scores < 0 

array([ True, False, False,  True, False,  True])

In [8]:
np.select([scores >=0, scores < 0],["so duong", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [9]:
scores  = np.array([-1, 1, 2, 0, -3, 5, 0, -4]) 
np.select([scores >0, scores ==0, scores < 0],["so duong", "so 0", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [10]:
import numpy as np    
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ]) 
print (D)

[[3 4]
 [5 6]]


In [11]:
C = np.mat(np.random.random((5,7)))
print (C)

[[0.41768769 0.70849971 0.54787942 0.71737203 0.64002539 0.10683086
  0.30363191]
 [0.54109933 0.80319934 0.94900812 0.38235887 0.89279777 0.10705633
  0.71898025]
 [0.39654878 0.45671069 0.41573037 0.15775992 0.24784098 0.52567094
  0.49942921]
 [0.30074892 0.27742179 0.3972608  0.67940496 0.69193305 0.14244301
  0.19081581]
 [0.78124368 0.22946698 0.67253473 0.32101048 0.7940614  0.30782155
  0.32953418]]


In [12]:
A = np.mat(np.random.random((2,2))) 
print (A)

[[0.8508041  0.77501268]
 [0.03010328 0.79064972]]


In [13]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)]) 
B = np.asmatrix(b) 
print (b) 

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [14]:
print (B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [15]:
A.T 

matrix([[0.8508041 , 0.03010328],
        [0.77501268, 0.79064972]])

In [16]:
A.I

matrix([[ 1.21758754, -1.19350675],
        [-0.04635856,  1.31022429]])

In [17]:
linalg.inv(A)
M = np.array([[-1,3,2],[0, -2,1],[1,5,-2]]) 
M_lower = np.tril(M) 
print(M_lower) 

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [18]:
M 	= 	np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M) 
print(M_upper) 

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [23]:
M 	= 	np.array([[-1,3,2],[0,-2,1],[1,5,-2]]) 
v_diag = np.diag(M)
print (v_diag) 

[-1 -2 -2]


In [21]:
print (M_diag) 

NameError: ignored