<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/chuong3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1. Một số phép xử lý ma trận của NumPy và Scipy
- Khởi tạo ma trận:

Khai báo thêm thư viện scipylinalg và một số các vector khởi tạo: 

In [2]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 

Các kiểu khai báo và khởi tạo ma trận: 

In [8]:
A = np.matrix(np.random.random( (2,2) ) ) 
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.mat(np.random.random( (10,5) ) ) 
D = np.mat([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0).
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Thử một số câu lệnh liên quan:

In [10]:
F = np.eye(3, k=0)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
F = np.eye(3, k=-1)
F

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- Các phép xử lý đơn giản 

In [20]:
# Xem hạng ma trận:
np.linalg.matrix_rank(C) 

5

In [21]:
# Tính ma trận nghịch đảo: 
A.I

matrix([[-2.85313535,  3.74684485],
        [ 6.47242683, -2.7166373 ]])

In [14]:
linalg.inv(A) # đây là lệnh của gói scipy, nên có thể sử dụng scipy.linalg.inv(A)

array([[-2.85313535,  3.74684485],
       [ 6.47242683, -2.7166373 ]])

In [22]:
# Định thức ma trận: 
linalg.det(A)

-0.06060515969539459

In [23]:
# Chuyển đổi ma trận: 
A.T #chuyển vị (dòng <=> cột)

matrix([[0.16464224, 0.39226246],
        [0.22707813, 0.17291472]])

In [25]:
# Chuyển đổi ma trận: 
A.H # chuyển vị liên hợp 

matrix([[0.16464224, 0.39226246],
        [0.22707813, 0.17291472]])

-  Giải các loại phương trình tuyến tính: 

In [19]:
linalg.solve(A, b) 

array([[-2.85313535-10.69083871j,  0.        +13.02795357j,
         0.        +13.92166308j],
       [ 6.47242683+47.38529232j,  0.         -0.63833282j,
         0.         +3.11745671j]])

In [26]:
E = np.mat(a).T 
E

matrix([[1],
        [2],
        [3]])

In [27]:
linalg.lstsq(F, E) 

(array([[2.],
        [3.],
        [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

- Các hàm trên ma trận 

Giới thiệu một số hàm trên ma trận. Các bạn sinh viên thực tập trên ma trận A và D khai
báo bên trên: 

In [28]:
# Cộng ma trận:
np.add(A, D) 

matrix([[4.16464224, 3.22707813],
        [2.39226246, 6.17291472]])

In [29]:
# Trừ ma trận:
np.subtract(A, D) 

matrix([[-3.83535776, -2.77292187],
        [-1.60773754, -5.82708528]])

In [30]:
# Chia ma trận: 
np.divide(A, D) 

matrix([[0.04116056, 0.07569271],
        [0.19613123, 0.02881912]])

In [31]:
# Nhân ma trận: 
A @ D # phiên bản Python 3.x

matrix([[1.11272521, 1.8563955 ],
        [1.91487929, 2.21427573]])

In [32]:
np.multiply(D, A) 

matrix([[0.65856895, 0.68123439],
        [0.78452492, 1.03748834]])

In [33]:
np.dot(A, D) 

matrix([[1.11272521, 1.8563955 ],
        [1.91487929, 2.21427573]])

In [34]:
np.vdot(A, D) 

matrix([[0.65856895]])

Hàm lũy thừa và logarith ma trận: 

In [37]:
linalg.expm(A) 

array([[1.23201653, 0.27283776],
       [0.4713092 , 1.24195605]])

In [38]:
linalg.logm(A)

array([[-1.41056784+1.59256381j,  0.48752029-1.19502627j],
       [ 0.84215908-2.0643289j , -1.39280741+1.54902885j]])

2. Tích (nhân) ma trận với ma trận

2.1. Nhân ma trận 

2.2. Ma trận khả nghịch 

2.3. Ma trận hội tụ

Ma trận phân kỳ:

In [40]:
 import numpy as np
 # Tính ma trận A:
A = np.array([ [0,1], [1,0]]) 
print(A) 

[[0 1]
 [1 0]]


In [41]:
temp = A.dot(A) # tính toan lần thứ 1 
print(temp) 

[[1 0]
 [0 1]]


In [42]:
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [43]:
# Tính ma trận B: 
B = np.array([ [0,-1], [-1,0]]) 
print(B) 

[[ 0 -1]
 [-1  0]]


In [44]:
temp = B.dot(B) # tính toan lần thứ 1
print(temp) 

[[1 0]
 [0 1]]


In [45]:
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


Ma trận hội tụ - Convergent matrix:

In [47]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ]) 
print(C) 

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [48]:
temp = C.dot(C) # tính toan lần thứ 1
print(temp) 

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [49]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
