<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/Chuong2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def scale(a, v): 
	return [a*vi for vi in v] 
v = [3,5,7] 
scale(10, v) 

[30, 50, 70]

In [ ]:
def sumvector(v, w):  
  return [vi+wi for (vi, wi) in zip(v, w)] 
v = [3,5,7] 
w = [2,4,6] 
sumvector(v, w) 

[5, 9, 13]

In [ ]:
def dotvector(v, w): 
  	return sum([vi*wi for (vi, wi) in zip(v, w)]) 
dotvector(v, w) 

68

In [ ]:
def lenvector(v):  
  return dotvector(v,v) 
lenvector(w) 

56

In [ ]:
import numpy as np 
scores  = np.array([-1, 1, 2, -3, 5, -4]) 

In [ ]:
scores >= 0 

array([False,  True,  True, False,  True, False])

In [ ]:
scores < 0 

array([ True, False, False,  True, False,  True])

In [ ]:
np.select([scores >=0, scores < 0],["so duong", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [ ]:
scores  = np.array([-1, 1, 2, 0, -3, 5, 0, -4]) 
np.select([scores >0, scores ==0, scores < 0],["so duong", "so 0", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [5]:
import numpy as np    
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ]) 
print (D)

[[3 4]
 [5 6]]


In [6]:
C = np.mat(np.random.random((5,7)))
print (C)

[[0.49687326 0.32370259 0.17844299 0.81903215 0.69938131 0.98907932
  0.95128913]
 [0.1745862  0.65930486 0.13210766 0.50865183 0.52466761 0.48393424
  0.18032213]
 [0.22978173 0.50651175 0.35212117 0.83675783 0.9810572  0.92815722
  0.34849762]
 [0.10465564 0.12679614 0.3470503  0.42344779 0.46832205 0.59293354
  0.28390926]
 [0.1456986  0.4522417  0.53302961 0.79872364 0.94792837 0.25406263
  0.33850443]]


In [7]:
A = np.mat(np.random.random((2,2))) 
print (A)

[[0.97645074 0.07992488]
 [0.71417895 0.39558935]]


In [8]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)]) 
B = np.asmatrix(b) 
print (b) 

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [9]:
print (B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [10]:
A.T 

matrix([[0.97645074, 0.71417895],
        [0.07992488, 0.39558935]])

In [12]:
A.I

matrix([[ 1.20169485, -0.24279045],
        [-2.16948505,  2.96619674]])

In [15]:
linalg.inv(A)
M = np.array([[-1,3,2],[0, -2,1],[1,5,-2]]) 
M_lower = np.tril(M) 
print(M_lower) 

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]
