<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/chuong3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.1. Một số phép xử lý ma trận của NumPy và Scipy
- Khởi tạo ma trận:

Khai báo thêm thư viện scipylinalg và một số các vector khởi tạo: 

In [2]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 

Các kiểu khai báo và khởi tạo ma trận: 

In [3]:
A = np.matrix(np.random.random( (2,2) ) ) 
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.mat(np.random.random( (10,5) ) ) 
D = np.mat([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0).
F

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Thử một số câu lệnh liên quan:

In [4]:
F = np.eye(3, k=0)
F

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
F = np.eye(3, k=-1)
F

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- Các phép xử lý đơn giản 

In [6]:
# Xem hạng ma trận:
np.linalg.matrix_rank(C) 

5

In [ ]:
# Tính ma trận nghịch đảo: 
A.I

matrix([[-2.85313535,  3.74684485],
        [ 6.47242683, -2.7166373 ]])

In [7]:
linalg.inv(A) # đây là lệnh của gói scipy, nên có thể sử dụng scipy.linalg.inv(A)

array([[-4.13697295,  2.48765292],
       [15.5680484 , -3.62266648]])

In [8]:
# Định thức ma trận: 
linalg.det(A)

-0.04212117552157913

In [9]:
# Chuyển đổi ma trận: 
A.T #chuyển vị (dòng <=> cột)

matrix([[0.15259097, 0.6557445 ],
        [0.10478287, 0.17425416]])

In [10]:
# Chuyển đổi ma trận: 
A.H # chuyển vị liên hợp 

matrix([[0.15259097, 0.6557445 ],
        [0.10478287, 0.17425416]])

-  Giải các loại phương trình tuyến tính: 

In [11]:
linalg.solve(A, b) 

array([[-4.13697295 -27.28214486j,  0.          +4.1643187j ,
         0.          +2.51499867j],
       [15.5680484 +125.62176967j,  0.         +13.02276439j,
         0.         +24.96814631j]])

In [12]:
E = np.mat(a).T 
E

matrix([[1],
        [2],
        [3]])

In [13]:
linalg.lstsq(F, E) 

(array([[2.],
        [3.],
        [0.]]), array([], dtype=float64), 2, array([1., 1., 0.]))

- Các hàm trên ma trận 

Giới thiệu một số hàm trên ma trận. Các bạn sinh viên thực tập trên ma trận A và D khai
báo bên trên: 

In [14]:
# Cộng ma trận:
np.add(A, D) 

matrix([[4.15259097, 3.10478287],
        [2.6557445 , 6.17425416]])

In [16]:
# Trừ ma trận:
np.subtract(A, D) 

matrix([[-3.84740903, -2.89521713],
        [-1.3442555 , -5.82574584]])

In [15]:
# Chia ma trận: 
np.divide(A, D) 

matrix([[0.03814774, 0.03492762],
        [0.32787225, 0.02904236]])

In [17]:
# Nhân ma trận: 
A @ D # phiên bản Python 3.x

matrix([[0.81992961, 1.0864701 ],
        [2.97148632, 3.01275848]])

In [18]:
np.multiply(D, A) 

matrix([[0.61036388, 0.3143486 ],
        [1.311489  , 1.04552498]])

In [19]:
np.dot(A, D) 

matrix([[0.81992961, 1.0864701 ],
        [2.97148632, 3.01275848]])

In [20]:
np.vdot(A, D) 

matrix([[0.61036388]])

Hàm lũy thừa và logarith ma trận: 

In [21]:
linalg.expm(A) 

array([[1.20538947, 0.12480568],
       [0.78104983, 1.23119225]])

In [22]:
linalg.logm(A)

array([[-1.61373147+1.63564923j,  0.29146367-0.62737502j],
       [ 1.82401675-3.92619267j, -1.55347321+1.50594342j]])

2. Tích (nhân) ma trận với ma trận

2.1. Nhân ma trận 

2.2. Ma trận khả nghịch 

2.3. Ma trận hội tụ

Ma trận phân kỳ:

In [23]:
 import numpy as np
 # Tính ma trận A:
A = np.array([ [0,1], [1,0]]) 
print(A) 

[[0 1]
 [1 0]]


In [24]:
temp = A.dot(A) # tính toan lần thứ 1 
print(temp) 

[[1 0]
 [0 1]]


In [25]:
k= 6
for i in range(k-1):
 temp = temp.dot(A)
 print (temp)
 print('---')

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [26]:
# Tính ma trận B: 
B = np.array([ [0,-1], [-1,0]]) 
print(B) 

[[ 0 -1]
 [-1  0]]


In [27]:
temp = B.dot(B) # tính toan lần thứ 1
print(temp) 

[[1 0]
 [0 1]]


In [28]:
k= 5
for i in range(k-1):
 temp = temp.dot(B)
 print (temp)
 print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


Ma trận hội tụ - Convergent matrix:

In [29]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ]) 
print(C) 

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [30]:
temp = C.dot(C) # tính toan lần thứ 1
print(temp) 

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [31]:
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


In [32]:
k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp) 

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.4	Ma trận Markov 

In [33]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [34]:
MM = M.dot(M) # tính M3
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [35]:
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

[[0.6 0.6]
 [0.4 0.4]]


3. Phương trình ma trận

3.1. Khái niệm về tách ma trận 

3.2. Phân rã ma trận LU

In [36]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)

[[1. 0.]
 [0. 1.]]


In [37]:
print (L)

[[1.   0.  ]
 [0.25 1.  ]]


In [40]:
print (U)

[[0.8   0.3  ]
 [0.    0.625]]


In [41]:
L.dot(U) 

array([[0.8, 0.3],
       [0.2, 0.7]])

4. Bài toán ứng dụng 1 – Căn bản về mật mã học, mã hóa thông tin, mật khẩu 

5. Bài toán ứng dụng 2 – Bài toán loan tin

In [42]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = A^22
print(temp) 

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [43]:
temp = temp.dot(A) # lúc này temp = A^33
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [44]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
