<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/Chuong2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def scale(a, v): 
	return [a*vi for vi in v] 
v = [3,5,7] 
scale(10, v) 

[30, 50, 70]

In [ ]:
def sumvector(v, w):  
  return [vi+wi for (vi, wi) in zip(v, w)] 
v = [3,5,7] 
w = [2,4,6] 
sumvector(v, w) 

[5, 9, 13]

In [ ]:
def dotvector(v, w): 
  	return sum([vi*wi for (vi, wi) in zip(v, w)]) 
dotvector(v, w) 

68

In [ ]:
def lenvector(v):  
  return dotvector(v,v) 
lenvector(w) 

56

In [ ]:
import numpy as np 
scores  = np.array([-1, 1, 2, -3, 5, -4]) 

In [ ]:
scores >= 0 

array([False,  True,  True, False,  True, False])

In [ ]:
scores < 0 

array([ True, False, False,  True, False,  True])

In [ ]:
np.select([scores >=0, scores < 0],["so duong", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so am', 'so duong', 'so am'],
      dtype='<U8')

In [ ]:
scores  = np.array([-1, 1, 2, 0, -3, 5, 0, -4]) 
np.select([scores >0, scores ==0, scores < 0],["so duong", "so 0", "so am"]) 

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U8')

In [ ]:
import numpy as np    
from scipy import linalg, sparse
D = np.mat([ [3,4], [5,6] ]) 
print (D)

[[3 4]
 [5 6]]


In [ ]:
C = np.mat(np.random.random((5,7)))
print (C)

[[0.21926902 0.52503521 0.59121954 0.51780828 0.84212749 0.2228611
  0.01048409]
 [0.56352056 0.30408573 0.91320892 0.78891068 0.24963946 0.046328
  0.8778773 ]
 [0.65627348 0.86605079 0.36074884 0.56884123 0.05570356 0.55677592
  0.44361873]
 [0.25968776 0.48342509 0.5128664  0.07671608 0.00451245 0.40375803
  0.32833395]
 [0.66940665 0.49840975 0.58331043 0.34917602 0.96127602 0.45420557
  0.07499299]]


In [ ]:
A = np.mat(np.random.random((2,2))) 
print (A)

[[0.79060369 0.25587658]
 [0.55567326 0.62477818]]


In [ ]:
b = np.array([(1+5j, 2j, 3j),(4, 5, 6)]) 
B = np.asmatrix(b) 
print (b) 

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
