<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/Chuong5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.	Sử dụng array và matrix trong numpy 

1.1.	Thông tin tóm gọn 

In [4]:
import numpy as np

In [7]:
D = np.array([[1,2],[3,4]])
np.copyto(E, D) 

In [6]:
E = np.array([[1,2],[3,5]]) 
np.copyto(E, D) 

In [9]:
print(E) 

[[1 2]
 [3 4]]


1.2.	Nên và không nên sử dụng kiểu dữ liệu numpy.matrix 

In [24]:
B = np.matrix("[1 2 3; 4 5 6]") 
x = np.array([['a','b'],['c','d']]) 
y = 'x'
C = np.matrix([[x,y],[1, 2]])
print(C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


In [25]:
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])

ValueError: ignored

In [26]:
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])    
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


1.3.	Đối tượng matrix từ các hàm trong gói numpy.matlib 

In [28]:
from numpy import matlib
G = matlib.identity(5)
print(G)   # cú pháp: matlib.identity(n) >>> print (G) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
H = matlib.randn(3,2) # cú pháp: matlib.randn(*args) 
print(H) 

[[ 1.51736995 -0.33982492]
 [ 1.33593819 -1.26212234]
 [-1.8209754   0.05977798]]


In [30]:
K = matlib.zeros([4,4])  #  cú pháp: matlib.zeros(shape) 
print(K) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


2.	Ứng dụng 2 –Liên phân số và số  

2.1.	Liên phân số 

2.2.	Liên phân số biểu diễn số  

In [32]:
import numpy as np 
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]   # thử chạy nhiều lần với dãy c dài khác nhau! >>> M = np.mat([[1,2],[3,4]])  # khởi tạo ma trận 2x2 
for i in range(len(c)): 
  ci = np.mat([[1,1],[1,0]])
  ci[0, 0] = c[i] 
  if (i==0): 
    M = ci 
  else: 
    M = M.dot(ci) 
print(M) 
print (M[0,0]/M[1,0])  # in số Pi theo dãy số  biểu diễn liên phân số. 

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


3.	Về phân tích hồi quy tuyến tính 

3.1.	Dẫn nhập: khái niệm về sai số 

3.2.	Phương pháp bình phương cực tiểu (mô hình tuyến tính) 