<a href="https://colab.research.google.com/github/ysneef/Daisotuyentinhvaungdung/blob/main/ktra-ctdlgt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(2, size=(6,6))
n=len(a)
for i in range(n):
    a[i][i]=0
for i in range (n):
    for j in range (n):
        if (a[i][j]== a[j][i]) and (a[i][j]==1):
            a[j][i]=0 
for i in range (n):
    for j in range (n):
        if (a[i][j]== 1):
            a[i][j]= np.random.randint(10, size=1)
print(a)

[[0 0 2 0 7 7]
 [0 0 5 0 0 3]
 [0 0 0 9 3 0]
 [0 0 0 0 0 4]
 [0 1 0 0 0 0]
 [0 0 0 0 0 0]]
